# Generated by Django 5.1.3 on 2024-11-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(null=True, upload_to='users/photos/'),
        ),
    ]
