# Generated by Django 5.1.3 on 2024-12-16 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honbs', '0002_alter_user_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Geladeira')),
                ('quantidade_prateleiras', models.IntegerField(verbose_name='Quantidade de Prateleiras')),
                ('numero', models.CharField(max_length=50, verbose_name='Número da Geladeira')),
            ],
        ),
        migrations.CreateModel(
            name='HemocomponentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prateleira_id', models.IntegerField(verbose_name='ID da Prateleira')),
                ('hemocomponente_id', models.IntegerField(verbose_name='ID do Hemocomponente')),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honbs.fridge', verbose_name='Geladeira')),
            ],
        ),
    ]
