# Generated by Django 5.1.3 on 2024-12-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honbs', '0003_fridge_hemocomponentstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='hemocomponentstock',
            name='quantidade',
            field=models.IntegerField(default=5, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
