# Generated by Django 5.1.3 on 2024-12-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honbs', '0004_hemocomponentstock_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridge',
            name='numero',
        ),
    ]
