# Generated by Django 5.1.3 on 2025-02-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honbs', '0006_geladeira_drawer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hemocomponentstock',
            name='fridge',
        ),
        migrations.DeleteModel(
            name='Fridge',
        ),
        migrations.DeleteModel(
            name='HemocomponentStock',
        ),
    ]
